insert into Audit_Questions values(1,'Internal','1.Have all Change requests followed SDLC before PROD move?','NO');
insert into Audit_Questions values(2,'Internal','2.Have all Change requests been approved by the application owner? ','NO');
insert into Audit_Questions values(3,'Internal','3.Are all artifacts like CR document, Unit test cases available? ','NO');
insert into Audit_Questions values(4,'Internal','4.Is the SIT and UAT sign-off available? ','NO');
insert into Audit_Questions values(5,'Internal','5.Is data deletion from the system done with application owner approval? ','NO');
insert into Audit_Questions values(6,'SOX','1.Have all Change requests followed SDLC before PROD move?','NO');
insert into Audit_Questions values(7,'SOX','2.Have all Change requests been approved by the application owner? ','NO');
insert into Audit_Questions values(8,'SOX','3.For a major change, was there a database backup taken before and after PROD move? ','NO');
insert into Audit_Questions values(9,'SOX','4.Has the application owner approval obtained while adding a user to the system? ','NO');
insert into Audit_Questions values(10,'SOX','5.Is data deletion from the system done with application owner approval? ','NO');